name: CI
on:
  push:
  pull_request:
    branches: [ main ]
  release:
    types: [ published ]

jobs:
  build:
    name: Build
    runs-on: macos-latest
    steps:
      - name: Check out Code
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install Dependencies
        run: brew bundle install
      - name: Add Nova to PATH
        run: echo "/Applications/Nova.app/Contents/SharedSupport" >> "$GITHUB_PATH"
      - name: Build Extension
        run: make build
      - name: Validate Extension
        if: startsWith(github.event.ref, 'refs/tags/')
        run: make validate
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Beancount.novaextension
          path: |
            build
            !build/*
            build/Beancount.novaextension
          if-no-files-found: error

  publish:
    name: Publish Extension
    needs: build
    if: github.event_name == 'release' && github.event.action == 'published'
    runs-on: macos-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: Beancount.novaextension
      - name: Install Nova
        run: brew install --cask nova
      - name: Validate Extension
        run: nova extension validate Beancount.novaextension
      - name: Publish Extension
        run: nova extension publish --no-confirm Beancount.novaextension
      - name: Package Extension
        run: zip -r Beancount.novaextension.zip Beancount.novaextension/
      - name: Upload Release Assets
        run: gh release upload "$GITHUB_REF_NAME" Beancount.novaextension.zip
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
